message: Hi Spring Cloud Config

server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chaminduonline/spring-cloud-config
          search-paths:
           - '*service'
