message: Hi Spring boot cloud config - chamindu online
server:
  port: 8094

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_practise?useSSL=false
    username: root
    password: Pa$$w0rd
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
